#!bin/bash
echo -e " "
killall php
echo -e " "

Logo () {
    white='\e[1;37m'
    green='\e[0;32m'
    blue='\e[1;34m'
    red='\e[1;31m'
    yellow='\e[1;33m'
    echo ""
    echo -e "\e[95m                       \e[33m                                                              
    ██████   █████  ██████  ██   ██     ██     ██ ███████ ██████  
    ██   ██ ██   ██ ██   ██ ██  ██      ██     ██ ██      ██   ██ 
    ██   ██ ███████ ██████  █████       ██  █  ██ █████   ██████  
    ██   ██ ██   ██ ██   ██ ██  ██      ██ ███ ██ ██      ██   ██ 
    ██████  ██   ██ ██   ██ ██   ██      ███ ███  ███████ ██████  \e[0m\n"
    echo -e "\e[95m \e[0m\n"
    echo -e $'\e[1;33m\e[0m\e[1;31m  ██████████\e[0m'"\e[1;37m██████████"'\e[1;33m\e[0m\e[0;32m██████████\e[0m' '\e[1;95m\e[0m\e[1;32m Host Dark Website \e[0m''\e[1;37m\e[0m\e[1;37m \e[0m'                                       
    echo ""
    sleep 1                                               
}

clear
Logo

echo -e " "
cd web || exit 1
php -S 127.0.0.1:8080 > /dev/null 2>&1 &
echo ""
echo -e $'\e[1;33m[\e[0m\e[1;91m*\e[0m\e[1;33m]\e[0m\e[1;32m Starting Server ... \e[0m'
echo ""
sleep 3
echo -e "\033[1;93mYou can check your server by accessing \e[34mhttp://127.0.0.1:8080"
echo -e " "
echo -e $'\e[1;33m[\e[0m\e[1;91m*\e[0m\e[1;33m]\e[0m\e[1;32m Done ! \e[0m'
